### ISSUE TITLE
Updating the User Interface [ Up for grabs] 

### ISSUE THREAD

**Issue by Saviour1001** [Saviour1001/StakeOverflow#10]
### Description

Currently the React Application is in a very simple UI, it can be upgraded to look much better with CSS and adding more UI libraries like Material UI and stuff.

**Comment by PeritusDeveloper** [comment]
Should I also add contribution.md ?

**Comment by Saviour1001** [comment]
Sure go ahead. Make a PR will have a look !!

**Comment by PeritusDeveloper** [comment]
I am trying to run the react app but I get the following error on running **npm install**

![image](https://user-images.githubusercontent.com/89828000/156528798-09d9797a-69c5-4456-a450-6766dd3e0a2f.png)

How do I resolve it?

**Comment by Saviour1001** [comment]
One of the reasons why Yarn is better than NPM. Yarn takes care of the dependency versions for you. 
How to solve the query. 
- Install yarn 
- yarn install 

Should solve

**Comment by PeritusDeveloper** [comment]
I tried installing yarn but still it is showing same error.
You can assign it to some other.

**Comment by Saviour1001** [comment]
Might wanna try pulling the code again, I fixed some stuff. It did work for me and some other contributors. 

Just in case I am using node version v16.13.2
