### ISSUE TITLE
Adding search function[Create New Issue]: 

### ISSUE THREAD

**Issue by SrushtiKakade28** [Saviour1001/StakeOverflow#11]
### Description

Description hey! @Saviour1001 This is my first time contributing to open source, I have followed the read me setup ,should I start with adding the search  bar?

**Comment by Saviour1001** [comment]
Sure go ahead. The data is getting indexed from the contract for showcasing the feed.
I guess you will need to make the search function and run it over the indexed data.

**Comment by SrushtiKakade28** [comment]
okayy!
