### ISSUE TITLE
Want to get involved with the project

### ISSUE THREAD

**Issue by Jassi10000** [Saviour1001/StakeOverflow#6]
@Saviour1001 Hey buddy am a GSSOC contributor , wanted to ask about the progress of project  ?
As this project is mentioned as one of the projects in GSSOC Project List , plus the tech used really interests me

**Comment by Saviour1001** [comment]
@Jassi10000 I updated the readme along with the steps to run it on local machine. Make issues regarding the future plans listed on readme and you can start contributing.
